# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: nucleus
    files:
      - ./src/main/resources/application.yml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - ./resources/deployment.yaml
