apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nucleus
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: nucleus
              servicePort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: nucleus
  labels:
    app: nucleus
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 32280
      protocol: TCP
    - name: debug
      port: 5005
      nodePort: 32250
      protocol: TCP
  selector:
    app: nucleus

---

# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nucleus
  labels:
    app: nucleus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nucleus
  template:
    metadata:
      labels:
        app: nucleus
    spec:
      containers:
        - name: nucleus
          image: localhost:5000/nucleus
          ports:
            - containerPort: 8080
